version: '3.7'
services:
    database:
        volumes:
            - data:/var/lib/mysql
            - ./init.sql:/data/application/init.sql
        image: 'mysql:latest'
        command: --init-file /data/application/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
            - '3306'

    maildev:
        image: maildev/maildev
        ports:
            - "1080:1080"
            - "1025:1025"
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: database
            ADMINER_DEFAULT_USERNAME: root
            ADMINER_DEFAULT_PASSWORD: password
            ADMINER_DESIGN: pepa-linha
volumes:
    data:
        driver: local
